name: TEST

on:
  push:
    branches:
      - master
      - env-*
    tags:
      - prod-*
      - staging-*
      - dev-*

env:
  TEST1: kamilbiela,testaccount

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - name: Check actor
        uses: actions/github-script@v7
        with:
          script: |
            console.log("test");
            console.log(context.actor);
            console.log(context);

      - name: Maybe fail test
        uses: actions/github-script@v7
        with:
          script: |
            if (process.env.TEST1.split(',').includes(context.actor) === false) {
              core.setFailed("Not authorized to deploy to production");
            }
            
            return false;

      - run: echo "ok"